fixtures:
  forge_modules:
    stdlib: "puppetlabs/stdlib"

  repositories:
 
# role module layout, include profile base and ntp module
    profile_base: "https://github.com/relybv/beng-profile_base.git"
    ntp: "https://github.com/puppetlabs/puppetlabs-ntp.git"
    rspec_monitor: "git://github.com/pgomersbach/test-rspec_monitor.git"

  symlinks:
    role_deployserver: "#{source_dir}"
