fixtures:
  repositories:
    profile_base: "https://github.com/relybv/beng-profile_base.git"
    stdlib:
      repo: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
      ref: "4.13.1"
    ntp:
      repo: "https://github.com/puppetlabs/puppetlabs-ntp.git"
      ref: "4.2.0"
    puppet: "https://github.com/abstractitptyltd/abstractit-puppet.git"
    inifile: "https://github.com/puppetlabs/puppetlabs-inifile.git"
    apt: "https://github.com/puppetlabs/puppetlabs-apt.git"
    profile_puppetmaster: "https://github.com/relybv/beng-profile_puppetmaster.git"
    apache:
      repo:  "https://github.com/puppetlabs/puppetlabs-apache.git"
      ref:  "1.4.1"
    puppetserver_gem: "https://github.com/puppetlabs/puppetlabs-puppetserver_gem.git"
    puppetdb: "https://github.com/puppetlabs/puppetlabs-puppetdb.git"
    firewall: "https://github.com/puppetlabs/puppetlabs-firewall.git"
    postgresql:
      repo:  "https://github.com/puppetlabs/puppetlabs-postgresql.git"
      ref: "4.9.0"
    concat:
      repo:  "https://github.com/puppetlabs/puppetlabs-concat.git"
      ref: "1.2.2"
    cron: "https://github.com/roman-mueller/rmueller-cron"
    snmp: "https://github.com/razorsedge/puppet-snmp.git"
    vmwaretools: "https://github.com/craigwatson/puppet-vmwaretools.git"
    openvmtools: "https://github.com/razorsedge/puppet-openvmtools.git"
    vsftpd: "https://github.com/thias/puppet-vsftpd.git"
    beng_nrpe: "https://github.com/relybv/beng-beng_nrpe.git"
    beng_fw: "https://github.com/relybv/beng-beng_fw.git"
    beng_vmware: "https://github.com/relybv/beng-beng_vmware.git"

  symlinks:
    role_deployserver: "#{source_dir}"
